--Acompanhamento de pedidos diarios 

SELECT
A.NUMPED,
A.CODCLI,
B.CLIENTE,
A.VLTOTAL,
C.NOME

FROM PCPEDC A JOIN PCCLIENT B
ON A.CODCLI = B.CODCLI
JOIN PCUSUARI C
ON C.CODUSUR = A.CODUSUR
WHERE A.DATA = TRUNC(SYSDATE)
