SELECT * FROM 
    (SELECT TO_NUMBER(TO_CHAR(P.DATA,'MM')) AS MES,
    P.CODUSUR RCA,
    U.NOME,
    C.CODCLI,
    C.FANTASIA,
    C.MUNICENT CIDADE,
    C.BAIRROENT BAIRRO,
    C.DTULTCOMP,
    SUM (P.VLATEND) VALOR
   FROM PCPEDC P,  PCCLIENT C, PCUSUARI U 
    WHERE P.CODCLI = C.CODCLI
    AND P.CODUSUR = C.CODUSUR1
    AND P.CODUSUR = U.CODUSUR
    and p.data between '01/JAN/2020' and '31/JAN/2020'
    GROUP BY TO_CHAR(P.DATA,'MM'),
   P.CODUSUR, U.NOME, C.CODCLI, C.CLIENTE,C.FANTASIA, C.DTULTCOMP, C.MUNICENT, C.BAIRROENT)
   PIVOT(SUM(VALOR) FOR MES IN (01 AS "JANEIRO", 02 AS "FEVEREIRO", 03 AS "MARÇO", 04 AS "ABRIL",
    05 AS "MAIO", 06 AS "JUNHO", 07 AS "JULHO",
    08 AS "AGOSTO", 09 AS "SETEMBRO", 10 AS "OUTUBRO", 1 AS "NOVEMBRO", 12 AS "DEZEMBRO"))
    ORDER BY RCA, CIDADE,BAIRRO
