SELECT
A.numnota,
--A.CODCLI,
--D.CLIENTE,
--B.descricao,
A.TIPOFJ,
A.CONSUMIDORFINAL,
ROUND((B.QTCONT * (B.PUNITCONT - NVL(B.VLIPI, 0) - NVL(B.ST, 0))),2) VLITEM,

(B.QTCONT * NVL(B.VLFRETE, 0)) VLFRETE,
 
(B.QTCONT * B.VLOUTRASDESP) VLOUTRASDESP,
 
NVL(B.PERCIPI, 0) PERCIPI,

DECODE(NVL(C.PERDIFEREIMENTOICMS,0), 100, 0, NVL(B.PERCICM, 0)) PERCICM,
 
DECODE(NVL(C.PERDIFEREIMENTOICMS,0), 100, 0, ROUND((NVL(B.BASEICMS,0)+NVL(C.VLBASEOUTROS,0)+ NVL(C.VLBASEFRETE, 0))* B.QTCONT,2)) VLBASE, 

DECODE(NVL(C.PERDIFEREIMENTOICMS,0),100,0,ROUND(((ROUND((NVL(B.BASEICMS,0)+NVL(C.VLBASEOUTROS,0)+NVL(C.VLBASEFRETE,0)) * B.QTCONT,2)* 
NVL(B.PERCICM,0)/100)- ROUND((NVL(C.VLICMSDIFERIDO,0) * 
B.QTCONT),2)),2)) VLICMS,

ROUND((B.QTCONT * NVL(B.ST, 0)),2) VLST,

--(B.QTCONT * (B.PUNITCONT + NVL(B.VLOUTROS,0))),
 
(B.QTCONT * (B.PUNITCONT + NVL(B.VLOUTROS,0)+ NVL(B.VLFRETE, 0)))  VLTOTAL,

B.SITTRIBUT,
 
(B.QTCONT * NVL(B.VLDESCONTO, 0)) VLDESCONTO, 
B.NBM,
 
B.IVA, 

B.DESCRICAO,
 
(B.CODPROD || ' - ' || B.DESCRICAO) PRODUTO, 

(A.CODCLI || ' - ' || A.CLIENTE) EMITENTE, 

B.CODST,


/*(SELECT SITTRIBUT 
                  FROM PCDESTSITTRIBUT 
                  WHERE NVL(VLISENTAS, 'N') = 'S'),

                        GREATEST(B.QTCONT * (B.PUNITCONT - NVL(B.ST, 0) - 
NVL(B.VLIPI, 0) -                                  NVL(B.VLDIFALIQUOTAS, 0)) - 
                                 B.QTCONT * NVL(B.BASEICMS, 0), 0),*/
             



round(B.qtcont * (nvl(B.punitcont,0) - nvl(B.st,0) - nvl(B.vlipi,0)),2) +
round((nvl(B.qtcont,0) * nvl(B.st,0)),2) +
round((nvl(B.qtcont,0) * nvl(B.vlipi,0)),2) +
round((nvl(B.qtcont,0) * nvl(B.vloutros,0)),2) +
decode(A.chavenfe, null, nvl(B.qtcont,0) * NVL(B.VLACRESCIMOPF, 0), 0) +
round((nvl(B.qtcont,0) * nvl(B.vlfrete,0)),2),2 AS VLDESDOBRADO, C.ORIGMERCTRIB
 


FROM PCNFSAID A, 
     PCMOV B, 
     PCMOVCOMPLE C, 
     PCCLIENT D, 
     PCFILIAL E
WHERE A.NUMTRANSVENDA = B.NUMTRANSVENDA 
AND B.NUMTRANSITEM = C.NUMTRANSITEM 
AND B.NUMNOTA = A.NUMNOTA
AND A.CODCLI = D.CODCLI 
--AND A.DTSAIDA BETWEEN '21JAN-2020' AND '22-JAN-2020'
AND A.DTSAIDA = TRUNC(SYSDATE)
AND A.ESPECIE IN ('NF', 'NC') 
AND B.QTCONT > 0
AND B.STATUS IN ('A', 'AB') 
AND B.DTCANCEL IS NULL 
AND A.DTCANCEL IS NULL 
GROUP BY 

A.numnota,
A.CODCLI,
D.CLIENTE,
B.descricao,
A.TIPOFJ,
A.CONSUMIDORFINAL,
B.QTCONT,
B.PUNITCONT,
B.VLIPI,
B.ST,
B.VLFRETE,
B.VLOUTRASDESP,
B.PERCIPI,
C.PERDIFEREIMENTOICMS,
B.PERCICM,
B.BASEICMS,
C.VLBASEOUTROS,
C.VLBASEFRETE,
C.VLICMSDIFERIDO,
B.VLOUTROS,
B.SITTRIBUT,
B.VLDESCONTO,
B.NBM,
B.IVA,
B.CODPROD,
A.CLIENTE,
B.CODST,
A.chavenfe,
B.VLACRESCIMOPF,
C.ORIGMERCTRIB,
B.VLDIFALIQUOTAS


ORDER BY
NUMNOTA
